{
    "name": "Codestra Integration Hub",
    "version": "19.0.1.0.1",
    "author": "Codestra",
    "category": "Codestra/Integration",
    "license": "LGPL-3",
    "depends": ["codestra_base", "codestra_vicidial_crm", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/sequence.xml",
        "data/cron.xml",
        "views/event_views.xml",
        "views/delivery_views.xml",
        "views/dead_letter_views.xml",
        "views/mapping_views.xml",
        "views/endpoint_views.xml",
        "views/audit_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
