{
    "name": "Codestra Identity Provisioning",
    "version": "19.0.1.7.0",
    "category": "Administration",
    "summary": "Fail-closed, audited multi-system identity provisioning",
    "license": "LGPL-3",
    "author": "Codestra",
    "depends": [
        "base",
        "mail",
        "contacts",
        "hr",
        "auth_signup",
        "web",
        "codestra_base",
        "call_center_core",
        "call_center_campaign",
        "codestra_cc_security",
        "codestra_cc_core",
    ],
    "data": [
        "security/provisioning_security.xml",
        "security/rbac_security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/safety_flags.xml",
        "views/provisioning_views.xml",
        "views/agent_channel_views.xml",
        "views/platform_user_views.xml",
        "views/tenant_views.xml",
        "views/platform_admin_menu.xml",
        "views/provisioning_wizard_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
}
