{
    "name": "Call Center Core",
    "version": "19.0.2.0.2",
    "category": "Sales/CRM",
    "summary": "Business units, security roles, and audit foundations",
    "author": "Codestra",
    "license": "LGPL-3",
    "depends": ["base", "mail", "crm", "contacts", "hr", "resource"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/business_units.xml",
        "data/feature_flags.xml",
        "data/canonical_statuses.xml",
        "views/business_unit_views.xml",
        "views/foundation_views.xml",
        "views/res_users_views.xml",
        "views/res_partner_views.xml",
        "views/crm_lead_views.xml",
        "views/audit_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
