{
    "name": "Codestra Contact Center Customer 360",
    "summary": "Chronological customer interaction and business-context facade",
    "version": "19.0.1.1.0",
    "author": "Codestra",
    "license": "LGPL-3",
    "depends": [
        "codestra_cc_core",
        "codestra_cc_crm",
        "codestra_cc_helpdesk",
        "codestra_interaction_workflow",
        "codestra_mail_inbox",
        "crm",
        "contacts",
        "mail",
    ],
    "data": [],
    "installable": True,
    "application": False,
}
