{
    "name": "Call Center Campaign",
    "version": "19.0.5.2.1",
    "category": "Sales/CRM",
    "summary": "Campaigns, teams, scripts, and lifecycle stages",
    "author": "Codestra",
    "license": "LGPL-3",
    "depends": ["call_center_core"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/lifecycle_stages.xml",
        "data/lifecycle_stage_mappings.xml",
        "data/multi_business_master_data.xml",
        "data/campaign_mapping_projection.xml",
        "views/campaign_views.xml",
        "views/foundation_views.xml",
        "views/script_views.xml",
        "views/crm_lead_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
