#!/usr/bin/env python3
"""Derive Odoo's read-side schemas from the pinned calling authority, never a fork."""
import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / 'contracts/vendor/calling-contract-authority'
ADDON = ROOT / 'custom-addons/codestra_vicidial_crm'


def generated():
    import yaml  # Authoring dependency only; CI checks the reviewed artifact lock.
    api = yaml.safe_load((VENDOR / 'contracts/telephony/codestra-calling-api.v1.openapi.yaml').read_text())
    events = yaml.safe_load((VENDOR / 'contracts/telephony/codestra-calling-events.v1.asyncapi.yaml').read_text())
    lock = json.loads((ROOT / '.codestra/calling-contract.lock.json').read_text())
    def resolve(value, source):
        if isinstance(value, list):
            return [resolve(item, source) for item in value]
        if not isinstance(value, dict):
            return value
        if '$ref' in value:
            node = source
            for part in value['$ref'].removeprefix('#/').split('/'):
                node = node[part]
            return resolve(node, source)
        if 'allOf' in value:
            assert len(value['allOf']) == 1
            return resolve(value['allOf'][0], source)
        return {key: resolve(item, source) for key, item in value.items() if key not in ('description', 'title')}
    result = {'digest': lock['sha256'], 'version': lock['version'], 'schemas': {}}
    for source, names in [(api, ['RealtimeSessionRequest', 'RealtimeSession', 'Operation']),
                          (events, ['AgentEventEnvelope', 'RealtimeControlEvent'])]:
        for name in names:
            result['schemas'][name] = resolve(source['components']['schemas'][name], source)
    result['operations'] = {
        operation['operationId']: {'method': method.upper(), 'path': path,
                                  'scope': operation.get('security', api['security'])[0]['oidc'][0]}
        for path, methods in api['paths'].items()
        for method, operation in methods.items()
        if isinstance(operation, dict) and operation.get('operationId') in ('createRealtimeSession', 'getTelephonyOperation')
    }
    # The operation name is itself authority data; locate the status route by path.
    path = '/v1/telephony/operations/{operation_id}'
    operation = api['paths'][path]['get']
    result['operations']['readOperation'] = {'method': 'GET', 'path': path, 'scope': operation.get('security', api['security'])[0]['oidc'][0]}
    encoded = json.dumps(result, sort_keys=True, indent=2) + '\n'
    outputs = {
        ADDON / 'models/calling_schema.json': encoded,
        ADDON / 'static/src/js/calling_schema.js': '/** @odoo-module **/\n// Generated by scripts/generate_calling_client_schema.py.\nexport const callingSchema = ' + encoded.rstrip() + ';\n',
    }

    manifest = {
        'authority_digest': lock['sha256'],
        'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'outputs': {str(path.relative_to(ROOT)): hashlib.sha256(content.encode()).hexdigest()
                    for path, content in outputs.items()},
    }
    outputs[ROOT / '.codestra/calling-client-schema.lock.json'] = json.dumps(manifest, sort_keys=True, indent=2) + '\n'
    return outputs


def check():
    # Source-head CI is deliberately stdlib-only. The reviewed lock binds the
    # generator, authority digest, and both generated runtime copies. Regeneration
    # uses PyYAML locally; this check requires no package downloads or network.
    manifest = json.loads((ROOT / '.codestra/calling-client-schema.lock.json').read_text())
    authority = json.loads((ROOT / '.codestra/calling-contract.lock.json').read_text())
    assert manifest['authority_digest'] == authority['sha256']
    assert manifest['generator_sha256'] == hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    assert set(manifest['outputs']) == {
        'custom-addons/codestra_vicidial_crm/models/calling_schema.json',
        'custom-addons/codestra_vicidial_crm/static/src/js/calling_schema.js',
    }
    for path, digest in manifest['outputs'].items():
        assert hashlib.sha256((ROOT / path).read_bytes()).hexdigest() == digest, path


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        check()
    else:
        for path, content in generated().items():
            path.write_text(content)
    print('CALLING_CLIENT_SCHEMA=PASS')
